import { Chamber, Member, PeerSupportItem, ContextualVouch, TrustTrailEvent, RecognitionBadge } from './types';

export const CURRENT_USER: Member = {
  id: 'usr-1',
  name: 'Alex Chen',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  role: 'Full-Stack Fellow',
  handle: '@alexchen.dev',
  cohort: 'Fall Fellowship 2026',
  roomNumber: 'Room B-2',
  stipendSchedule: 'Monthly (28th)',
  stipendFrequency: 'Monthly (28th)',
};

export const FELLOW_MEMBERS: Member[] = [
  CURRENT_USER,
  {
    id: 'usr-2',
    name: 'Sarah Okonjo',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=256',
    role: 'Backend & Cloud Fellow',
    handle: '@sarahecho',
    cohort: 'Fall Fellowship 2026',
    roomNumber: 'Room B-1',
    stipendSchedule: 'Bi-weekly (Fridays)',
    stipendFrequency: 'Bi-weekly (Fridays)',
  },
  {
    id: 'usr-3',
    name: 'Marcus Kamau',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    role: 'Mobile & Systems Intern',
    handle: '@kamau_builds',
    cohort: 'Fall Fellowship 2026',
    roomNumber: 'Room B-3',
    stipendSchedule: 'Monthly (1st)',
    stipendFrequency: 'Monthly (1st)',
  },
  {
    id: 'usr-4',
    name: 'Devin Thorne',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    role: 'Security & DevOps Fellow',
    handle: '@dthorne',
    cohort: 'Fall Fellowship 2026',
    roomNumber: 'Room B-4',
    stipendSchedule: 'Monthly (25th)',
    stipendFrequency: 'Monthly (25th)',
  },
];

export const INITIAL_CHAMBER: Chamber = {
  id: 'chamber-4b',
  name: 'Chamber 4B — Dev Hive Hub',
  unit: 'Unit 4B (4-Fellow Suite)',
  address: '34 Tech Haven Way, Innovation District',
  totalMonthlyRent: 2400,
  currency: 'USD',
  nextDueDate: 'October 1, 2026',
  cycleProgressPercent: 75,
  members: FELLOW_MEMBERS,
  utilities: [
    {
      name: 'Gigabit Fiber Internet',
      amount: 120,
      splitPerPerson: 30,
      status: 'collected',
      dueDate: 'Sept 25, 2026',
    },
    {
      name: 'Hydro & Electricity',
      amount: 180,
      splitPerPerson: 45,
      status: 'pending',
      dueDate: 'Sept 29, 2026',
    },
    {
      name: 'Common Supplies & Water Filter',
      amount: 40,
      splitPerPerson: 10,
      status: 'collected',
      dueDate: 'Sept 20, 2026',
    },
  ],
};

export const INITIAL_SUPPORT_ITEMS: PeerSupportItem[] = [
  {
    id: 'sup-1',
    toMemberId: 'usr-1',
    toMemberName: 'Alex Chen',
    toMemberAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    type: 'loan',
    title: 'Shortfall buffer before stipend clears',
    description: 'My internship stipend arrives on the 28th, but our chamber rent share ($600) is due on the 25th. Looking for a $200 short-term bridge.',
    amount: 200,
    currency: 'USD',
    repaymentExpected: true,
    repaymentDueDate: 'Sept 29, 2026 (Stipend arrival)',
    status: 'fulfilled',
    createdAt: '2 days ago',
    category: 'rent',
    vouchCount: 3,
  },
  {
    id: 'sup-2',
    toMemberId: 'usr-3',
    toMemberName: 'Marcus Kamau',
    toMemberAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    type: 'contribution',
    title: 'Backup 5G router for hackathon week',
    description: 'Pool for a prepaid unlimited 5G backup device for all 4 fellows during the regional demo sprint.',
    amount: 60,
    currency: 'USD',
    repaymentExpected: false,
    status: 'open',
    createdAt: 'Yesterday',
    category: 'utilities',
    vouchCount: 2,
  },
  {
    id: 'sup-3',
    toMemberId: 'usr-2',
    toMemberName: 'Sarah Okonjo',
    toMemberAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=256',
    type: 'gift',
    title: 'Late night hack fuel & meal basket',
    description: 'Shared espresso beans and pantry essentials gifted to support anyone pulling late shifts on open-source repositories.',
    amount: 35,
    currency: 'USD',
    repaymentExpected: false,
    status: 'fulfilled',
    createdAt: '3 days ago',
    category: 'food',
    vouchCount: 4,
  },
  {
    id: 'sup-4',
    toMemberId: 'usr-4',
    toMemberName: 'Devin Thorne',
    toMemberAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    type: 'mentorship',
    title: 'Docker & Soroban Smart Contract Architecture',
    description: 'Offering 1-on-1 walkthrough of stateful testing for fellows preparing for next week evaluation.',
    currency: 'USD',
    repaymentExpected: false,
    status: 'open',
    createdAt: '5 hours ago',
    category: 'certification',
    vouchCount: 5,
  },
];

export const INITIAL_VOUCHES: ContextualVouch[] = [
  {
    id: 'vch-1',
    voucherId: 'usr-2',
    voucherName: 'Sarah Okonjo',
    voucherAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=256',
    targetMemberId: 'usr-1',
    targetMemberName: 'Alex Chen',
    context: 'Chamber 4B Roommate & Rent Accountability',
    confidenceLevel: 'high',
    commitmentReference: 'Rent cycle Aug-Sept 2026',
    timestamp: 'Sept 12, 2026',
    note: 'Alex always communicates stipend timing 4+ days in advance. Consistently dependable on shared chamber utilities.',
  },
  {
    id: 'vch-2',
    voucherId: 'usr-3',
    voucherName: 'Marcus Kamau',
    voucherAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    targetMemberId: 'usr-1',
    targetMemberName: 'Alex Chen',
    context: 'Open-Source Sprint & Peer Loan Settlement',
    confidenceLevel: 'high',
    commitmentReference: 'Hardware repair bridge $150',
    timestamp: 'Aug 29, 2026',
    note: 'Borrowed $150 for screen fix, repaid 2 days before the agreed date without needing reminders.',
  },
  {
    id: 'vch-3',
    voucherId: 'usr-4',
    voucherName: 'Devin Thorne',
    voucherAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    targetMemberId: 'usr-2',
    targetMemberName: 'Sarah Okonjo',
    context: 'Chamber Coordinator & Common Inventory',
    confidenceLevel: 'solid',
    commitmentReference: 'Broadband switchover contract',
    timestamp: 'Sept 5, 2026',
    note: 'Organized our router migration, verified all bills transparently with receipts.',
  },
];

export const INITIAL_TRAIL_EVENTS: TrustTrailEvent[] = [
  {
    id: 'evt-101',
    timestamp: 'Today at 09:14 AM',
    type: 'repayment_fulfilled',
    actorName: 'Alex Chen',
    actorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    title: 'Peer Loan Repayment Completed',
    details: 'Repaid $200 loan to Sarah Okonjo for chamber rent bridge ahead of agreed due date.',
    amount: 200,
    hash: '0x8f4d...3e79',
    isPrivate: false,
    verified: true,
    evidenceRef: 'TX-SEP26-9921',
  },
  {
    id: 'evt-102',
    timestamp: 'Yesterday at 04:30 PM',
    type: 'repair_completed',
    actorName: 'Marcus Kamau',
    actorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    title: 'Commitment Repaired & Resolved',
    details: 'Communication flagged delayed stipend on Sept 18. Revised due date set for Sept 22. Full $45 utility share settled.',
    amount: 45,
    hash: '0x3c2a...b712',
    isPrivate: false,
    verified: true,
    repairRef: 'RP-2026-CH4B',
  },
  {
    id: 'evt-103',
    timestamp: '3 days ago',
    type: 'vouch_issued',
    actorName: 'Sarah Okonjo',
    actorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=256',
    title: 'Contextual Vouch Submitted for Alex Chen',
    details: 'Confidence: High. Context: Chamber rent accountability and stipend schedule honesty.',
    hash: '0x7e11...902a',
    isPrivate: false,
    verified: true,
  },
  {
    id: 'evt-104',
    timestamp: 'Sept 1, 2026',
    type: 'payment_recorded',
    actorName: 'Chamber 4B (All Members)',
    actorAvatar: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=256',
    title: 'September Suite Rent Disbursed ($2,400)',
    details: 'All 4 fellows settled on time. Master receipt anchored to verification log.',
    amount: 2400,
    hash: '0x19fa...881c',
    isPrivate: false,
    verified: true,
    evidenceRef: 'RECEIPT-SEPT-4B-PROP',
  },
  {
    id: 'evt-105',
    timestamp: 'Aug 28, 2026',
    type: 'due_date_renegotiated',
    actorName: 'Alex Chen',
    actorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
    title: 'Due Date Adjusted With Mutual Consent',
    details: 'Notice given 6 days prior to landlord due date. Chamber agreed to interim 3-day extension.',
    hash: '0x66de...4411',
    isPrivate: true,
    verified: true,
  },
];

export const RECOGNITION_SIGNALS: RecognitionBadge[] = [
  {
    id: 'sig-1',
    title: 'Consistent Rent Accountability',
    description: 'Fulfilled 4 consecutive chamber rent payment cycles on or before scheduled dates.',
    category: 'commitments',
    earnedDate: 'September 2026',
    verifiedTrailCount: 6,
  },
  {
    id: 'sig-2',
    title: 'Proactive Communication in Difficulty',
    description: 'Reported timing friction >48h in advance with transparent revised timeline and completed full repair.',
    category: 'communication',
    earnedDate: 'August 2026',
    verifiedTrailCount: 3,
  },
  {
    id: 'sig-3',
    title: 'Thoughtful Vouch Steward',
    description: 'Provided 3 contextual, high-accuracy peer evaluations backed by real shared experiences.',
    category: 'vouching',
    earnedDate: 'July 2026',
    verifiedTrailCount: 5,
  },
  {
    id: 'sig-4',
    title: 'Community Knowledge Contributor',
    description: 'Organized open-source code sprints and assisted 3 fellow interns during hardware setups.',
    category: 'stewardship',
    earnedDate: 'September 2026',
    verifiedTrailCount: 4,
  },
];
